---
title: "<center> <h1>***SIZECONTEMO - STIMULI***</h1> </center>"
author: '[Antonio Schettino](https://www.researchgate.net/profile/Antonio_Schettino2 "Antonio Schettino")'
date: '`r Sys.Date()`'
output:
  html_document:
    theme: united
    highlight: tango
    code_folding: hide
    toc: true
    toc_float: true
---

In this project we will investigate the electrophysiological correlates of the combined processing of basic visual properties (i.e., size and contrast) and the emotional content of simple words. 

In this document we will provide details on the parameters of the selected words.

```{r setup_environment,echo=FALSE,warning=FALSE,message=FALSE}
# setup work environment
# dev.off() # clear plots (if no plots are present, comment it out or it will throw an error)
cat("\014") # clear console
rm(list=ls()) # clear environment
set.seed(9001) # specify seed for RNG and ensure reproducible results (it's over 9000!)

expname <- "SizeContEmo" # experiment name
wd <- paste("D:/OneDrive - UGent/",expname,"/task/",sep="") # work directory
setwd(wd) # set work directory

# load relevant libraries
library(knitr) # dynamic report generation
library(Rmisc) # for advanced summary functions
library(yarrr) # amazing graphs
library(BayesFactor) # calculate Bayes factors
library(fitdistrplus) # fit parametric distributions to non-censored or censored data
```

```{r setup_output}
# setup report output
options(width=120,scipen=999,digits=3) # change output width (for better printing), disable scientific notation (default: scipen=0), constrain output to 4 decimals
opts_chunk$set(warning=FALSE,message=FALSE,fig.width=10,fig.height=6) # for each chunk, display the output but not the R code (echo=FALSE), no package warnings (message=FALSE), no package messages (message=FALSE), width and height of all figures
```

```{r main_data}
wordparam <- read.csv("240samplenomen_pluslocalizer.csv",header=TRUE) # load data





```






